CREATE DATABASE Roman;
GO

USE Roman;
GO

CREATE TABLE TiposUsuarios (
	Id INT IDENTITY PRIMARY KEY NOT NULL,
	Descricao VARCHAR(120) UNIQUE NOT NULL
);

CREATE TABLE Usuarios (
	Id INT IDENTITY PRIMARY KEY NOT NULL,	
	Email VARCHAR(200) NOT NULL UNIQUE,
	Nome VARCHAR(200) NOT NULL,
	Senha VARCHAR(200) NOT NULL,
	TipoUsuarioId INT FOREIGN KEY REFERENCES TiposUsuarios(Id) NOT NULL
);

CREATE TABLE Equipes (
	Id INT IDENTITY PRIMARY KEY NOT NULL,
	Descricao VARCHAR(200) UNIQUE NOT NULL,
)

CREATE TABLE Professores (
	Id INT IDENTITY PRIMARY KEY NOT NULL,
	UsuariosId INT FOREIGN KEY REFERENCES Usuarios(Id) UNIQUE NOT NULL,
	EquipeId INT FOREIGN KEY REFERENCES Equipes(Id) NOT NULL
);

CREATE TABLE ProfessoresEquipes (	
	ProfessorId INT FOREIGN KEY REFERENCES Professores(Id) NOT NULL,
	EquipeId INT FOREIGN KEY REFERENCES Equipes(Id) NOT NULL
);

CREATE TABLE Administradores (
	Id INT IDENTITY PRIMARY KEY NOT NULL,
	UsuarioId INT FOREIGN KEY REFERENCES Usuarios(Id) NOT NULL
);

CREATE TABLE Temas (
	Id INT IDENTITY PRIMARY KEY,
	Tema VARCHAR(200) UNIQUE NOT NULL,
	Ativo BIT NOT NULL,
);

CREATE TABLE Projetos (
	Id INT IDENTITY PRIMARY KEY,
	Titutlo VARCHAR(200) UNIQUE NOT NULL,
	Descricao VARCHAR(700) NOT NULL,
	TemaId INT NOT NULL FOREIGN KEY REFERENCES Temas(Id),
	ProfessorId INT FOREIGN KEY REFERENCES Professores(Id) NOT NULL
);
