USE Roman;
GO

SELECT U.ID, U.EMAIL, U.NOME, T.TIPO, U.SENHA FROM USUARIOS U JOIN TIPO_USUARIOS T ON U.ID_TIPO_USUARIO = T.TIPO_USUARIO_ID;

SELECT * FROM USUARIOS;
SELECT * FROM TIPO_USUARIOS;
SELECT * FROM TEMAS;
SELECT * FROM PROJETOS;
SELECT * FROM PROFESSORES;
SELECT * FROM EQUIPES;

SELECT P.PROFESSOR_ID, U.NOME, E.EQUIPE FROM PROFESSORES P 
JOIN USUARIOS U ON U.ID = P.ID_USUARIO 
JOIN EQUIPES E ON E.EQUIPE = 'Desenvolvimento';

SELECT P.TITULO, P.DESCRICAO, U.NOME, T.TEMA FROM PROJETOS P 
JOIN TEMAS T ON P.ID_TEMA = T.TEMAID 
JOIN PROFESSOR_PROJETO PP ON PP.ID_PROJETO = P.PROJETO_ID 
JOIN USUARIOS U ON U.ID = PP.ID_PROFESSOR;